=== ntkctksnb1/LabCodeFpt/PRX301/Assigment1-XML/public_html/CustomerOrder.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="customer_order">
        <xs:complexType>
            <xs:sequence>

                <xs:element name = "lines" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "line" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name = "item" type="xs:string"></xs:element>
                                        <xs:element name = "quantity" type="xs:positiveInteger"></xs:element>
                                        <xs:element name = "price" type="price_type"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="no" type="xs:positiveInteger" use="required" ></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                
                <xs:element name = "customer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "name" type="xs:string"></xs:element>
                            <xs:element name = "street" type="xs:string"></xs:element>
                            <xs:element name = "city" type="xs:string"></xs:element>
                            <xs:element name = "post_code" type="post_code_type"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name = "payment">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "card_issuer" type="xs:string"></xs:element>
                            <xs:element name = "card_number" type="card_number_type"></xs:element>
                            <xs:element name = "expiration_date">
                                <xs:complexType>
                                    <xs:attribute name="month" type="month_type" ></xs:attribute>
                                    <xs:attribute name="year" type="year_type" ></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            
            <xs:attribute name="number" type="customer_number_type" use="required"></xs:attribute>
            <xs:attribute name="date" type="xs:date" use="required"></xs:attribute>
            
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="customer_number_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="post_code_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}-[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="card_number_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4} [0-9]{6} [0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="price_type">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:maxInclusive value="99999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="month_type">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="year_type">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9999"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== ntkctksnb1/LabCodeFpt/PRX301/Assigment1-XML/public_html/newXMLDocument1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="customer_order.xsl"?>
<customer_order
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='CustomerOrder.xsd'
    number="004985" date="2004-06-24" >
    <lines>
        <line no="1">
            <item>cd</item>
            <quantity>30</quantity>
            <price>0.95</price>
        </line>
        <line no="2">
            <item>CD RW</item>
            <quantity>20</quantity>
            <price>2.95</price>
        </line>
        <line no="3">
            <item>weeb</item>
            <quantity>1</quantity>
            <price>0.05</price>
        </line>
    </lines>
    <customer>
        <name>Tenich</name>
        <street>Nadbystrct 39</street>
        <city>Lblin</city>
        <post_code>20-501</post_code>
    </customer>
    <payment>
        <card_issuer>Master Card</card_issuer>
        <card_number>1234 567890 12345</card_number>
        <expiration_date month="10" year="2005"></expiration_date>
    </payment>

</customer_order>
